config/routes.rb
Rails.application.routes.draw do
  resources :search_content_for, only: [:index]
  root 'ads_items#index'

  scope '/:locale', locale: /en|ru/ do
    get 'ads_items', to: 'ads_items#index'
    get 'ads_items/search'
    get 'ads_items/user_page'
    resources :ads_items
    devise_for :users

    resource :user, only: %i[edit destroy] do
      collection do
        patch 'update_password'
        patch 'update_avatar'
        delete 'user_delete'
      end
    end
    resources :ads_items do
      patch :to_new
      patch :approve
      patch :decline
      patch :return
    end
    ActiveAdmin.routes(self)
  end
end

app/models/ads_item.rb
class AdsItem < ApplicationRecord
  include PgSearch
  include AASM

  belongs_to :user
  belongs_to :category, counter_cache: :count_of_ads

  validates :title, presence: true
  validates :title, length: { maximum: 100 }
  validates :text, length: { maximum: 300 }
  mount_uploaders :images, ImageUploader
  validates :category, presence: { message: (I18n.t 'category_cant_be_blank').to_s }

  aasm do
    state :draft, initial: true
    state :new
    state :approved
    state :refused
    state :archived

    event :to_new do
      transitions from: :draft, to: :new
    end

    event :approve do
      transitions from: :new, to: :approved
    end

    event :decline do
      transitions from: :new, to: :refused
    end

    event :return do
      transitions from: :new, to: :draft
    end
  end

  pg_search_scope :search, against: { title: 'A', text: 'B' },
                           using: { tsearch: { any_word: true, prefix: true},
                                    dmetaphone: { sort_only: true} }

  scope :approved_scope, -> { where(aasm_state: :approved) }
  scope :approved_new_scope, -> { where(aasm_state: [:approved, :new]) }

  def self.perform_search(keyword)
    if keyword.present?
      AdsItem.approved_new_scope.search(keyword)
    else
      AdsItem.approved_new_scope.all
    end
  end

  def self.filter(filter)
    where(category_id: filter) if filter
  end
end

app/controllers/ads_items_controller.rb
class AdsItemsController < ApplicationController
  attr_reader :user
  before_action :authenticate_user!, only: %i[new create edit update
                                              destroy to_new decline
                                              approve return]
  before_action :authenticate_admin!, only: %i[decline approve]
  before_action :find_by_id, only: %i[show edit update destroy]
  before_action :find_by_ads_item_id, only: %i[to_new decline approve return]
  helper_method :sort_column, :sort_direction

  def index
    @ads_item = AdsItem.new
    ads = if params[:sort] == 'date'
            policy_scope(AdsItem).order("approval_date #{sort_direction}")
          elsif params[:sort] == 'author'
            policy_scope(AdsItem).order("user_id #{sort_direction}")
          else
            policy_scope(AdsItem).order(approval_date: :desc)
          end
    @ads_items = ads.page params[:page]
  end

  def search
    col = sort_column == 'user_id' ? 'users.email' : sort_column
    if !params[:filter].nil? && params[:filter] != ''
      filtered = policy_scope(AdsItem).perform_search(params[:search])
                                      .filter(params[:filter])
    else
      filtered = policy_scope(AdsItem).perform_search(params[:search])
    end
    ads_items_ids = []
    filtered.each do |x|
      ads_items_ids << x.id
    end
    @num_categories = policy_scope(AdsItem).where('ads_items.id in (?)', ads_items_ids)
                                    .group(:category).count
    @ads_items = filtered.reorder("#{col} #{sort_direction}")
  end

  def show
  end

  def new
    @ads_item = AdsItem.new
    authorize @ads_item
  end

  def edit
    authorize @ads_item
  end

  def create
    @ads_item = AdsItem.new(ads_items_params)
    @ads_items = AdsItem.order(:title).page params[0]
    @ads_item.user = current_user
    authorize @ads_item
    if @ads_item.save
      redirect_back(fallback_location: root_path,
                    notice: (t 'ad.created').to_s)
    else
      render :new, notice: (t 'ad.not_created').to_s
    end
  end

  def update
    authorize @ads_item
    if @ads_item.update(permitted_attributes(@ads_item))
      @ads_item.update_attributes!(aasm_state: :draft, approval_date: :nil)
      redirect_back(fallback_location: root_path,
                    notice: (t 'ad.updated').to_s)
    else
      render :edit
    end
  end

  def destroy
    authorize @ads_item
    @ads_item.destroy
    redirect_to root_path, notice: (t 'ad.destroyed').to_s
  end

  def to_new
    authorize @ads_item
    @ads_item.update_attributes!(aasm_state: :new)
    redirect_back(fallback_location: root_path,
                  notice: (t 'ad.published').to_s)
  end

  def approve
    authorize @ads_item
    @ads_item.update_attributes!(aasm_state: :approved,
                                 approval_date: Time.zone.now)
    redirect_back(fallback_location: root_path,
                  notice: (t 'ad.approved').to_s)
   end

  def decline
    authorize @ads_item
    @ads_item.update(permitted_attributes(@ads_item))
    @ads_item.update_attributes!(aasm_state: :refused)
    redirect_back(fallback_location: root_path,
                  notice: (t 'ad.decline').to_s)
  end

  def return
    authorize @ads_item
    @ads_item.update_attributes!(aasm_state: :draft)
    redirect_back(fallback_location: root_path,
                  notice: (t 'ad.return_to_drafts').to_s)
  end

  private

  def find_by_id
    @ads_item = AdsItem.find(params[:id])
  end

  def find_by_ads_item_id
    @ads_item = AdsItem.find(params[:ads_item_id])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    AdsItem.column_names.include?(params[:sort]) ? params[:sort] : 'title'
  end

  def ads_items_params
    params.require(:ads_item).permit(:title,
                                     :text,
                                     :category_id,
                                     images: [])
  end
end

app/views/ads_items/_buttons.slim
.btn-group.btn-group-justified role="group"
  - if policy(item).to_new?
    = link_to "#{t('buttons.to_new')}", ads_item_to_new_url(item), method: :patch, :class => "btn btn-success"
  - if policy(item).update?
    = link_to "#{t('buttons.edit')}", edit_ads_item_url(item), :class => "btn btn-primary"
  - if policy(item).return?
    = link_to "#{t('buttons.return')}", ads_item_return_url(item), method: :patch, :class => "btn btn-warning"
  - if policy(item).destroy? && item.id != nil
    = link_to "#{t('buttons.delete')}", ads_item_url(item), method: :delete, data: { confirm: "#{t('are_you_sure')}" }, :class => "btn btn-danger"
- if policy(item).approve?
  .card-footer
    .btn-group aria-label=("Basic example") role="group" 
      - if policy(item).approve?
        = link_to "#{t('buttons.approve')}", ads_item_approve_url(item), method: :patch, :class => "btn btn-success"
      - if policy(item).decline?
        = link_to "#{t('buttons.decline')}", "javascript:void(0)", id: "comments-link", class: "btn btn-warning"
    #comments-form
      = form_for item, url: ads_item_decline_url(item), method: :patch  do |f|
        = f.text_field :comment, :class => 'form-control', :placeholder => "#{t 'enter_comment'}"
        button.btn.btn-primary type="f.submit" = t 'buttons.submit'

app/views/ads_items/_card_body.slim
.card-body
  h4.card-title
    = link_to(item) do
      = item.title
  -if locale == :ru
      p.card-text = item.category.ru
  - else
      p.card-text = item.category.en
  - if policy(item).destroy?
    .label.label-primary = I18n.t "states.#{item.aasm_state}"
  - if policy(item).update? && item.aasm_state == 'refused'
    = item.comment
  p.card-text= item.text
  = render :partial => "buttons", :object => item, locals: {item: item}
.card-footer
  - if item.aasm_state == 'approved'
    small.text-muted
      = "#{I18n.t'published_by'} #{item.user.email} #{I18n.t'at'} #{item.approval_date.strftime("%d.%m.%Y %H:%M")}"
  - else
    small.text-muted
      = "#{I18n.t'send_by'} #{item.user.email} #{I18n.t'at'} #{item.updated_at.strftime("%d.%m.%Y %H:%M")}"

app/views/ads_items/_card_image.slim
.card-body
  = link_to(item) do
    - if item.images.empty?
      img.card-img-top.img-fluid alt=("Card image") src="http://zametki.by/wp-content/themes/easymag/images/no-image.png" 
    - else
      = image_tag(item.images.first.url.to_s, class: 'card-img img-fluid mx-auto d-block')

app/views/ads_items/_card_images.slim
.card-body
  - item.images.each do |image|
    - if item.images.empty?
      img.card-img-top.img-fluid alt=("Card image") src="http://zametki.by/wp-content/themes/easymag/images/no-image.png" 
    - else
      = image_tag(image.url.to_s, class: 'card-img img-fluid mx-auto d-block')

app/views/ads_items/_form.slim
= form_for(@ads_item) do |f|
  .card
    .card-body
      - @ads_item.images.each do |image|
        = image_tag(image.url.to_s, class: 'card-img-top img-fluid mx-auto d-block')
      .field
        = t 'images'
        = f.file_field :images, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png"
        .form-group.has-error
          #helpBlock2.help-block
            = error_message_on(f.object, :image)
      .form-group
        = t 'title'
        - if @ads_item == nil
          br
            = f.text_field :title, :class => 'form-control', :placeholder => "#{t 'enter_title'}"
        - else
          = f.text_field :title, :class => 'form-control'
        .form-group.has-error
            #helpBlock2.help-block
              = error_message_on(f.object, :title)
      .form-group
        = t 'category'
        br
          = f.collection_select :category_id, Category.all, :id, locale
          .form-group.has-error
            #helpBlock2.help-block
              = error_message_on(f.object, :category)
      .form-group
        = t 'text'
        br
          = f.text_area :text, :class => 'form-control'
          .form-group.has-error
            #helpBlock2.help-block
              = error_message_on(f.object, :text)
      button.btn.btn-primary type="f.submit" = t'buttons.submit'
      .form-group
      small.text-muted
        = I18n.t 'message_for_user'

app/views/ads_items/_search.slim
table.table
  thead.pretty
    tr
      th
        = sortable "title", "#{I18n.t'title'}"
      th
        = sortable "approval_date", "#{I18n.t'approval_date'}"
      th
        = sortable "user_id", "#{I18n.t'author'}"
      th
        = sortable "category_id", "#{I18n.t'category'}"
  tbody
    - @ads_items.each do |item|
      tr
        td
          = link_to(item.title)
        td 
          = item.approval_date 
        td 
          = item.user.email 
        td 
          - if locale == :ru 
            = item.category.ru 
          -else 
            = item.category.en

app/views/ads_items/edit.html.slim
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6.text-center
    h4.display-4= @ads_item.title
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    = render :partial => "form", html: { multipart: true }
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    nav.breadcrumb
      = link_to "#{t('back')}", ads_items_path, class: "breadcrumb-item"
      span.breadcrumb-item.active= @ads_item.title

app/views/ads_items/index.html.slim
- if policy(@ads_item).create?
  = link_to "#{t'add_new_ad'}", "javascript:void(0)", id: "new-ad-link", class: "btn btn btn-primary"
  .row.justify-content-center
    .col-sm-12.offset-sm-0.col-md-6
      #new-ad-form
        h1= t 'new_ad'
        = render :partial => "form", html: { multipart: true }
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    h1.text-center=  t 'ads_board'
    ul.nav aria-label=("Page navigation example") 
      = paginate @ads_items
    ul.nav.nav-pills
      .btn-group role="group"
        a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="http://example.com" 
          = t 'sort_by'
        .dropdown-menu aria-labelledby="btnGroupDrop1" 
          li= link_to "#{t'sort.date'}", url_for( :sort => 'date', :direction => 'asc'),  autocomplete: "off", type: "checkbox"
          li= link_to "#{t'sort.author'}", url_for( :sort => 'author', :direction => 'asc'), autocomplete: "off", type: "checkbox"
      = link_to "▲", url_for( :sort => params[:sort], :direction => 'asc'), type: "link", class: "nav-link"
      = link_to "▼", url_for( :sort => params[:sort], :direction => 'desc'), type: "link", class: "nav-link"
      h5
        - if params[:sort] == nil
        - else
          = I18n.t('sorted_by'".""#{params[:sort]}")
    
    - @ads_items.each do |item|
      .card
        = render :partial => "card_image", locals: { item: item }
        = render :partial => "card_body", locals: { item: item }
    ul.nav aria-label=("Page navigation example") 
      = paginate @ads_items
    

app/views/ads_items/new.html.slim
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    h1= t 'new_ad'
    = render :partial => "form", html: { multipart: true }
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    nav.breadcrumb
      = link_to "#{t('back')}", ads_items_path, class: "breadcrumb-item"
      span.breadcrumb-item.active = I18n.t'new_ad'

app/views/ads_items/search.js.erb
$('#ads_items').html("<%= escape_javascript(render('search'))%>");

app/views/ads_items/search.slim
.row
  .col-sm-12.offset-sm-0.col-md-3
    = form_tag ads_items_search_url, remote: true, :method => :get, class: "form-filter" do
      = hidden_field_tag :sort, params[:sort]
      = hidden_field_tag :direction, params[:direction]
      = hidden_field_tag :search, params[:search]
      = radio_button_tag :filter, "", checked: true
      = label :filter, "#{t'select_all'}"
      - @num_categories.each do |key, value|
        p
          = radio_button_tag :filter, "#{key.id}", checked: true
          - if locale == :ru
            = label :filter, "#{key.ru}"
            | (#{value})
          - else
            = label :filter, "#{key.en}"
            | (#{value})
      p
        = submit_tag "#{t'buttons.filter'}", :class => "btn btn-primary"
  .col-sm-12.offset-sm-0.col-md-6
    .card
      .card-body
        #ads_items
          = render "search"
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    nav.breadcrumb
      = link_to "#{t('back')}", ads_items_path, class: "breadcrumb-item"
      span.breadcrumb-item.active = I18n.t'search_page'

app/views/ads_items/show.html.slim
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6.text-center
    h4.display-4= @ads_item.title
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    .card
      = render :partial => "card_image", object: @ads_item, :as => :item
      = render :partial => "card_body", object: @ads_item, :as => :item
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    nav.breadcrumb
      = link_to "#{t('back')}", ads_items_path, class: "breadcrumb-item"
      span.breadcrumb-item.active = @ads_item.title

app/views/ads_items/user_page.html.slim
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    h1= t 'user_page'
    .card.p-3
      p
        .form-inline
          = image_tag(current_user.avatar.url(:medium), class: "rounded float-left", align: "top")
          = form_for(current_user, :url => { :controller =>"users", :action => "update_avatar" }, html: { multipart: true }) do |f|
            = f.file_field :avatar
            = f.submit t('buttons.change_avatar'), class: "btn btn-md btn-primary btn-block"
        = form_for(current_user, :url => { :controller =>"users", :action => "user_delete" }) do |f|
          = f.password_field :current_password, autocomplete: "off", :class => 'form-control', :placeholder => "#{t 'password'}"
          = f.password_field :password, autocomplete: "off", :class => 'form-control', :placeholder => "#{t 'new_password'}"
          = f.password_field :password_confirmation, autocomplete: "off", :class => 'form-control', :placeholder => "#{t 'new_password_confirmation'}"
          = f.submit t('buttons.change_password'), class: "btn btn-md btn-primary btn-block"
      = link_to "#{t('buttons.delete_profile')}", user_delete_user_url(locale), method: :delete, data: { confirm: "#{t('are_you_sure')}" }, :class => "btn btn-danger"
    - current_user.ads_items.includes(:category).each do |item|
      .card
        = render :partial => "card_image", locals: { item: item }
        = render :partial => "card_body", locals: { item: item }
.row.justify-content-center
  .col-sm-12.offset-sm-0.col-md-6
    nav.breadcrumb
      = link_to "#{t('back')}", ads_items_path, class: "breadcrumb-item"
      span.breadcrumb-item.active = I18n.t'user_page'