config/routes.rb
Rails.application.routes.draw do
  resources :search_content_for, only: [:index]
  root 'ads_items#index'

  scope '/:locale', locale: /en|ru/ do
    get 'ads_items', to: 'ads_items#index'
    get 'ads_items/search'
    get 'ads_items/user_page'
    resources :ads_items
    devise_for :users

    resource :user, only: %i[edit destroy] do
      collection do
        patch 'update_password'
        patch 'update_avatar'
        delete 'user_delete'
      end
    end
    resources :ads_items do
      patch :to_new
      patch :approve
      patch :decline
      patch :return
    end
    ActiveAdmin.routes(self)
  end
end

app/views/layouts/_navigation.html.slim
.header.clearfix
  nav
    ul.nav.nav-pills.float-right
      - if user_signed_in?
        = image_tag(current_user.avatar.url(:medium), class: "round-image-40")
        = link_to "#{current_user.email}", ads_items_user_page_path, class: "nav-link"
        .nav-item.dropdown
          a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="http://example.com"
            = t 'language'
          .dropdown-menu aria-labelledby="navbarDropdownMenuLink" 
            - I18n.available_locales.each do |language|
              = link_to t("name", :locale => language) , url_for( :locale => language), class: "dropdown-item"
        - if current_user.try(:admin?)
          = link_to "#{t 'admin_page'}", admin_ads_items_path, class: "nav-link"
        = link_to "#{t 'log_out'}", destroy_user_session_path, method: :get, class: "nav-link"
      - else
        .nav-item.dropdown
          a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="http://example.com" 
            = t 'language'
          .dropdown-menu aria-labelledby="navbarDropdownMenuLink" 
            - I18n.available_locales.each do |language|
              = link_to t("name", :locale => language) , url_for(:locale => language), class: "dropdown-item"
        = link_to "#{t 'log_in'}", new_user_session_path, class: "nav-link"
        = link_to "#{t 'sign_up'}", new_user_registration_path, class: "nav-link"
    u1.nav.nav-pills.float-left
      = link_to 'Ads Board', ads_items_path(locale), :class => 'nav-link'
      .form-inline.my-2.my-lg-0
        = form_tag ads_items_search_path, :method => "get", id: "ads_item_search" do |f|
          = hidden_field_tag :sort, params[:sort] = nil
          = hidden_field_tag :direction, params[:direction] = nil
          = hidden_field_tag :filter, params[:filter] = nil
          = text_field_tag :search, "#{params[:search]}"
          = submit_tag "#{t'buttons.search'}", :name => nil, :class => "btn btn-link"
   

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=edge" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    /! The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags
    link href="/ab.ico" rel=("shortcut icon") type="image/x-icon" /
    title= t 'ads_board'
    link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" rel="stylesheet"
    script crossorigin="anonymous" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
    script crossorigin="anonymous" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" 
    script crossorigin="anonymous" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" 

    script crossorigin="anonymous" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" 
     

    /! HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    /! WARNING: Respond.js doesn't work if you view the page via file://
    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script
      | <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/navigation"
    .container
      #flash
        - flash.each do |key, value|
          div class=("alert alert-info alert-dismissible fade show #{key}") role="alert" 
            button.close aria-label="Close" data-dismiss="alert" type="button" 
              span aria-hidden="true"  ×
            = value
      = yield